name: CI

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  release:
    types:
      - published

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REPOSITORY: galaxy/docker-galaxy-microbiology-lab
  GALAXY_BASE_IMAGE: quay.io/bgruening/galaxy:25.1.1
  TOOL_FILE: local_tools.yml
  TOOL_FILE_MINIMAL: local_tools_minimal.yml


jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image (no push)
        uses: bgruening/docker-galaxy-github-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          tags: ci-${{ github.sha }}
          base-image: ${{ env.GALAXY_BASE_IMAGE }}
          push: false
          tool-file: ${{ env.TOOL_FILE_MINIMAL }}

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: quay.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        uses: bgruening/docker-galaxy-github-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          push: true
          base-image: ${{ env.GALAXY_BASE_IMAGE }}
          username: '$oauthtoken'
          password: ${{ secrets.QUAY_OAUTH_TOKEN }}
          tags: |
            ${{ github.event.release.tag_name }}
            latest
          tool-file: ${{ env.TOOL_FILE }}
